use motedb;

insert into college values ( 2,'img/colleges/Albright_College.jpg',' Albright College', 'en', 'US');  
insert into college values ( 3,'img/colleges/American_University.jpg',' American University', 'en', 'US');  
insert into college values ( 4,'img/colleges/Arizona_State.jpg',' Arizona State', 'en', 'US');  
insert into college values ( 5,'img/colleges/Assumption_College.jpg',' Assumption College', 'en', 'US');  
insert into college values ( 6,'img/colleges/Bentley_University.jpg',' Bentley University', 'en', 'US');  
insert into college values ( 7,'img/colleges/Binghamton_University.jpg',' Binghamton University', 'en', 'US');  
insert into college values ( 8,'img/colleges/Bloomsburg_U.jpg',' Bloomsburg U', 'en', 'US');  
insert into college values ( 9,'img/colleges/Boston_College.jpg',' Boston College', 'en', 'US');  
insert into college values ( 10,'img/colleges/Boston_University.jpg',' Boston University', 'en', 'US');  
insert into college values ( 11,'img/colleges/Bucknell_University.jpg',' Bucknell University', 'en', 'US');  
insert into college values ( 12,'img/colleges/Carnegie_Mellon_U.jpg',' Carnegie Mellon U', 'en', 'US');  
insert into college values ( 13,'img/colleges/Centenary_College.jpg',' Centenary College', 'en', 'US');  
insert into college values ( 14,'img/colleges/Clemson_University.jpg',' Clemson University', 'en', 'US');  
insert into college values ( 15,'img/colleges/Coastal_Carolina.jpg',' Coastal Carolina', 'en', 'US');  
insert into college values ( 16,'img/colleges/College_of_Charleston.jpg',' College of Charleston', 'en', 'US');  
insert into college values ( 17,'img/colleges/Colorado_School_of_Mines.jpg',' Colorado School of Mines', 'en', 'US');  
insert into college values ( 18,'img/colleges/Colorado_State_University.jpg',' Colorado State University', 'en', 'US');  
insert into college values ( 19,'img/colleges/County_College_of_Morris.jpg',' County College of Morris', 'en', 'US');  
insert into college values ( 20,'img/colleges/DeSales_University.jpg',' DeSales University', 'en', 'US');  
insert into college values ( 21,'img/colleges/Dickinson_College.jpg',' Dickinson College', 'en', 'US');  
insert into college values ( 22,'img/colleges/Drexel_U.jpg',' Drexel U', 'en', 'US');  
insert into college values ( 23,'img/colleges/Duke_University.jpg',' Duke University', 'en', 'US');  
insert into college values ( 24,'img/colleges/East_Carolina_University.jpg',' East Carolina University', 'en', 'US');  
insert into college values ( 25,'img/colleges/East_Stroudsburg_University.jpg',' East Stroudsburg University', 'en', 'US');  
insert into college values ( 26,'img/colleges/Elon_University.jpg',' Elon University', 'en', 'US');  
insert into college values ( 27,'img/colleges/Farleigh_Dickinson_U.jpg',' Farleigh Dickinson U', 'en', 'US');  
insert into college values ( 28,'img/colleges/Florida_College.jpg',' Florida College', 'en', 'US');  
insert into college values ( 29,'img/colleges/Florida_State_U.jpg',' Florida State U', 'en', 'US');  
insert into college values ( 30,'img/colleges/George_Washington_University.jpg',' George Washington University', 'en', 'US');  
insert into college values ( 31,'img/colleges/High_Point_University.jpg',' High Point University', 'en', 'US');  
insert into college values ( 32,'img/colleges/Hofstra_U.jpg',' Hofstra U', 'en', 'US');  
insert into college values ( 33,'img/colleges/Indiana_University.jpg',' Indiana University', 'en', 'US');  
insert into college values ( 34,'img/colleges/Indiana_University_of_Pennsylvania.jpg',' Indiana University of Pennsylvania', 'en', 'US');  
insert into college values ( 35,'img/colleges/ionic.png',' ionic', 'en', 'US');  
insert into college values ( 36,'img/colleges/Iowa.jpg',' Iowa', 'en', 'US');  
insert into college values ( 37,'img/colleges/Iowa_State.jpg',' Iowa State', 'en', 'US');  
insert into college values ( 38,'img/colleges/JMU.jpg',' JMU', 'en', 'US');  
insert into college values ( 39,'img/colleges/Johns_Hopkins_U.jpg',' Johns Hopkins U', 'en', 'US');  
insert into college values ( 40,'img/colleges/Kean_University.jpg',' Kean University', 'en', 'US');  
insert into college values ( 41,'img/colleges/Kent_State_University.jpg',' Kent State University', 'en', 'US');  
insert into college values ( 42,'img/colleges/Kings_College.jpg',' King''s College', 'en', 'US');  
insert into college values ( 43,'img/colleges/Kutztown_University.jpg',' Kutztown University', 'en', 'US');  
insert into college values ( 44,'img/colleges/La_Salle_University.jpg',' La Salle University', 'en', 'US');  
insert into college values ( 45,'img/colleges/Lehigh_University.jpg',' Lehigh University', 'en', 'US');  
insert into college values ( 46,'img/colleges/Liberty_University.jpg',' Liberty University', 'en', 'US');  
insert into college values ( 47,'img/colleges/Lock_Haven_u.jpg',' Lock Haven u', 'en', 'US');  
insert into college values ( 48,'img/colleges/Loyola.jpg',' Loyola', 'en', 'US');  
insert into college values ( 49,'img/colleges/Manhattan_College.jpg',' Manhattan College', 'en', 'US');  
insert into college values ( 50,'img/colleges/McDaniel_College.jpg',' McDaniel College', 'en', 'US');  
insert into college values ( 51,'img/colleges/mcfly.jpg',' mcfly', 'en', 'US');  
insert into college values ( 52,'img/colleges/Miami.jpg',' Miami', 'en', 'US');  
insert into college values ( 53,'img/colleges/Miami_U_of_Ohio.jpg',' Miami U of Ohio', 'en', 'US');  
insert into college values ( 54,'img/colleges/michigan_state.jpg',' michigan state', 'en', 'US');  
insert into college values ( 55,'img/colleges/Miseracordia_University.jpg',' Miseracordia University', 'en', 'US');  
insert into college values ( 56,'img/colleges/mississippi_state_university.jpg',' mississippi state university', 'en', 'US');  
insert into college values ( 57,'img/colleges/Monmouth_University.jpg',' Monmouth University', 'en', 'US');  
insert into college values ( 58,'img/colleges/Montclair_state.jpg',' Montclair state', 'en', 'US');  
insert into college values ( 59,'img/colleges/Moravian_College.jpg',' Moravian College', 'en', 'US');  
insert into college values ( 60,'img/colleges/NC_State.jpg',' NC State', 'en', 'US');  
insert into college values ( 61,'img/colleges/Northeastern_U.jpg',' Northeastern U', 'en', 'US');  
insert into college values ( 62,'img/colleges/Notre_Dame.jpg',' Notre Dame', 'en', 'US');  
insert into college values ( 63,'img/colleges/ohio_state.jpg',' ohio state', 'en', 'US');  
insert into college values ( 64,'img/colleges/Ohio_University.jpg',' Ohio University', 'en', 'US');  
insert into college values ( 65,'img/colleges/Old_Dominion_University.jpg',' Old Dominion University', 'en', 'US');  
insert into college values ( 66,'img/colleges/Penn_State.jpg',' Penn State', 'en', 'US');  
insert into college values ( 67,'img/colleges/Philadelphia_University.jpg',' Philadelphia University', 'en', 'US');  
insert into college values ( 68,'img/colleges/Princeton_University.jpg',' Princeton University', 'en', 'US');  
insert into college values ( 69,'img/colleges/Providence University',' P', 'en', 'US');  
insert into college values ( 70,'img/colleges/Ramapo.jpg',' Ramapo', 'en', 'US');  
insert into college values ( 71,'img/colleges/Rider_University.jpg',' Rider University', 'en', 'US');  
insert into college values ( 72,'img/colleges/Rowan_university.jpg',' Rowan university', 'en', 'US');  
insert into college values ( 73,'img/colleges/Rutgers.jpg',' Rutgers', 'en', 'US');  
insert into college values ( 74,'img/colleges/Saint_Josephs.jpg',' Saint Josephs', 'en', 'US');  
insert into college values ( 75,'img/colleges/Salisbury.jpg',' Salisbury', 'en', 'US');  
insert into college values ( 76,'img/colleges/San_Diego_State.jpg',' San Diego State', 'en', 'US');  
insert into college values ( 77,'img/colleges/Seton_Hall.jpg',' Seton Hall', 'en', 'US');  
insert into college values ( 78,'img/colleges/Shippensburg_U.jpg',' Shippensburg U', 'en', 'US');  
insert into college values ( 79,'img/colleges/Slippery_Rock_U.jpg',' Slippery Rock U', 'en', 'US');  
insert into college values ( 80,'img/colleges/South_Carolina.jpg',' South Carolina', 'en', 'US');  
insert into college values ( 81,'img/colleges/Stanford.jpg',' Stanford', 'en', 'US');  
insert into college values ( 82,'img/colleges/Stevens_Institute_of_Technology.jpg',' Stevens Institute of Technology', 'en', 'US');  
insert into college values ( 83,'img/colleges/Stony_Brook_u.jpg',' Stony Brook u', 'en', 'US');  
insert into college values ( 84,'img/colleges/Syracuse.jpg',' Syracuse', 'en', 'US');  
insert into college values ( 85,'img/colleges/Temple_University.jpg',' Temple University', 'en', 'US');  
insert into college values ( 86,'img/colleges/Texas_AM_University.jpg',' Texas AM University', 'en', 'US');  
insert into college values ( 87,'img/colleges/The_Citadel.jpg',' The Citadel', 'en', 'US');  
insert into college values ( 88,'img/colleges/The_College_of_New_Jersey.jpg',' The College of New Jersey', 'en', 'US');  
insert into college values ( 89,'img/colleges/Thumbs.db',' Thumbs', 'en', 'US');  
insert into college values ( 90,'img/colleges/Towson_University.jpg',' Towson University', 'en', 'US');  
insert into college values ( 91,'img/colleges/UCLA.jpg',' UCLA', 'en', 'US');  
insert into college values ( 92,'img/colleges/University_of_ Buffalo.jpg',' University of  Buffalo', 'en', 'US');  
insert into college values ( 93,'img/colleges/University_of_Arizona.jpg',' University of Arizona', 'en', 'US');  
insert into college values ( 94,'img/colleges/University_of_Central_Florida.jpg',' University of Central Florida', 'en', 'US');  
insert into college values ( 95,'img/colleges/University_of_Cincinnati.jpg',' University of Cincinnati', 'en', 'US');  
insert into college values ( 96,'img/colleges/University_of_Colorado.jpg',' University of Colorado', 'en', 'US');  
insert into college values ( 97,'img/colleges/University_of_Connecticut.jpg',' University of Connecticut', 'en', 'US');  
insert into college values ( 98,'img/colleges/university_of_deleware.jpg',' university of deleware', 'en', 'US');  
insert into college values ( 99,'img/colleges/university_of_Florida.jpg',' university of Florida', 'en', 'US');  
insert into college values ( 100,'img/colleges/University_of_Georgia.jpg',' University of Georgia', 'en', 'US');  
insert into college values ( 101,'img/colleges/University_of_Houston.jpg',' University of Houston', 'en', 'US');  
insert into college values ( 102,'img/colleges/University_of_Illinois.jpg',' University of Illinois', 'en', 'US');  
insert into college values ( 103,'img/colleges/University_of_Kansas.jpg',' University of Kansas', 'en', 'US');  
insert into college values ( 104,'img/colleges/University_of_Maine.jpg',' University of Maine', 'en', 'US');  
insert into college values ( 105,'img/colleges/university_of_maryland.jpg',' university of maryland', 'en', 'US');  
insert into college values ( 106,'img/colleges/University_of_Michigan.jpg',' University of Michigan', 'en', 'US');  
insert into college values ( 107,'img/colleges/University_of_Minnesota.jpg',' University of Minnesota', 'en', 'US');  
insert into college values ( 108,'img/colleges/University_of_Mississippi.jpg',' University of Mississippi', 'en', 'US');  
insert into college values ( 109,'img/colleges/University_of_New_Hampshire.jpg',' University of New Hampshire', 'en', 'US');  
insert into college values ( 110,'img/colleges/University_of_New_Haven.jpg',' University of New Haven', 'en', 'US');  
insert into college values ( 111,'img/colleges/University_of_North_Carolina.jpg',' University of North Carolina', 'en', 'US');  
insert into college values ( 112,'img/colleges/University_of_Pittsburgh.jpg',' University of Pittsburgh', 'en', 'US');  
insert into college values ( 113,'img/colleges/University_of_Rhode_Island.jpg',' University of Rhode Island', 'en', 'US');  
insert into college values ( 114,'img/colleges/University_of_Richmond.jpg',' University of Richmond', 'en', 'US');  
insert into college values ( 115,'img/colleges/University_of_Scranton.jpg',' University of Scranton', 'en', 'US');  
insert into college values ( 116,'img/colleges/University_of_Tampa.jpg',' University of Tampa', 'en', 'US');  
insert into college values ( 117,'img/colleges/university_of_virginia.jpg',' university of virginia', 'en', 'US');  
insert into college values ( 118,'img/colleges/UNLV.jpg',' UNLV', 'en', 'US');  
insert into college values ( 119,'img/colleges/UPENN.jpg',' UPENN', 'en', 'US');  
insert into college values ( 120,'img/colleges/USC.jpg',' USC', 'en', 'US');  
insert into college values ( 121,'img/colleges/VCU.jpg',' VCU', 'en', 'US');  
insert into college values ( 122,'img/colleges/Villanova_University.jpg',' Villanova University', 'en', 'US');  
insert into college values ( 123,'img/colleges/Virginia_Tech.jpg',' Virginia Tech', 'en', 'US');  
insert into college values ( 124,'img/colleges/Wake_Forest_University.jpg',' Wake Forest University', 'en', 'US');  
insert into college values ( 125,'img/colleges/Western_Carolina_U.jpg',' Western Carolina U', 'en', 'US');  
insert into college values ( 126,'img/colleges/West_Chester_University.jpg',' West Chester University', 'en', 'US');  
insert into college values ( 127,'img/colleges/Widener_University.jpg',' Widener University', 'en', 'US');  
insert into college values ( 128,'img/colleges/William_Patterson_U.jpg',' William Patterson U', 'en', 'US');  
insert into college values ( 129,'img/colleges/Wisconsin.jpg',' Wisconsin', 'en', 'US');  
insert into college values ( 130,'img/colleges/WVU.jpg',' WVU', 'en', 'US');  
insert into college values ( 131,'img/colleges/Xavier_University.jpg',' Xavier University', 'en', 'US');  
insert into college values ( 132,'img/colleges/Yale_University.jpg',' Yale University', 'en', 'US'); 