use motedb;

insert into college values ( 1,'img/colleges/Albright_College.jpg',' Albright College');  
insert into college values ( 2,'img/colleges/American_University.jpg',' American University');  
insert into college values ( 3,'img/colleges/Arizona_State.jpg',' Arizona State');  
insert into college values ( 4,'img/colleges/Assumption_College.jpg',' Assumption College');  
insert into college values ( 5,'img/colleges/Bentley_University.jpg',' Bentley University');  
insert into college values ( 6,'img/colleges/Binghamton_University.jpg',' Binghamton University');  
insert into college values ( 7,'img/colleges/Bloomsburg_U.jpg',' Bloomsburg U');  
insert into college values ( 8,'img/colleges/Boston_College.jpg',' Boston College');  
insert into college values ( 9,'img/colleges/Boston_University.jpg',' Boston University');  
insert into college values ( 10,'img/colleges/Bucknell_University.jpg',' Bucknell University');  
insert into college values ( 11,'img/colleges/Carnegie_Mellon_U.jpg',' Carnegie Mellon U');  
insert into college values ( 12,'img/colleges/Centenary_College.jpg',' Centenary College');  
insert into college values ( 13,'img/colleges/Clemson_University.jpg',' Clemson University');  
insert into college values ( 14,'img/colleges/Coastal_Carolina.jpg',' Coastal Carolina');  
insert into college values ( 15,'img/colleges/College_of_Charleston.jpg',' College of Charleston');  
insert into college values ( 16,'img/colleges/Colorado_School_of_Mines.jpg',' Colorado School of Mines');  
insert into college values ( 17,'img/colleges/Colorado_State_University.jpg',' Colorado State University');  
insert into college values ( 18,'img/colleges/County_College_of_Morris.jpg',' County College of Morris');  
insert into college values ( 19,'img/colleges/DeSales_University.jpg',' DeSales University');  
insert into college values ( 20,'img/colleges/Dickinson_College.jpg',' Dickinson College');  
insert into college values ( 21,'img/colleges/Drexel_U.jpg',' Drexel U');  
insert into college values ( 22,'img/colleges/Duke_University.jpg',' Duke University');  
insert into college values ( 23,'img/colleges/East_Carolina_University.jpg',' East Carolina University');  
insert into college values ( 24,'img/colleges/East_Stroudsburg_University.jpg',' East Stroudsburg University');  
insert into college values ( 25,'img/colleges/Elon_University.jpg',' Elon University');  
insert into college values ( 26,'img/colleges/Farleigh_Dickinson_U.jpg',' Farleigh Dickinson U');  
insert into college values ( 27,'img/colleges/Florida_College.jpg',' Florida College');  
insert into college values ( 28,'img/colleges/Florida_State_U.jpg',' Florida State U');  
insert into college values ( 29,'img/colleges/George_Washington_University.jpg',' George Washington University');  
insert into college values ( 30,'img/colleges/High_Point_University.jpg',' High Point University');  
insert into college values ( 31,'img/colleges/Hofstra_U.jpg',' Hofstra U');  
insert into college values ( 32,'img/colleges/Indiana_University.jpg',' Indiana University');  
insert into college values ( 33,'img/colleges/Indiana_University_of_Pennsylvania.jpg',' Indiana University of Pennsylvania');  
insert into college values ( 34,'img/colleges/ionic.png',' ionic');  
insert into college values ( 35,'img/colleges/Iowa.jpg',' Iowa');  
insert into college values ( 36,'img/colleges/Iowa_State.jpg',' Iowa State');  
insert into college values ( 37,'img/colleges/JMU.jpg',' JMU');  
insert into college values ( 38,'img/colleges/Johns_Hopkins_U.jpg',' Johns Hopkins U');  
insert into college values ( 39,'img/colleges/Kean_University.jpg',' Kean University');  
insert into college values ( 40,'img/colleges/Kent_State_University.jpg',' Kent State University');  
insert into college values ( 41,'img/colleges/Kings_College.jpg',' King''s College');  
insert into college values ( 42,'img/colleges/Kutztown_University.jpg',' Kutztown University');  
insert into college values ( 43,'img/colleges/La_Salle_University.jpg',' La Salle University');  
insert into college values ( 44,'img/colleges/Lehigh_University.jpg',' Lehigh University');  
insert into college values ( 45,'img/colleges/Liberty_University.jpg',' Liberty University');  
insert into college values ( 46,'img/colleges/Lock_Haven_u.jpg',' Lock Haven u');  
insert into college values ( 47,'img/colleges/Loyola.jpg',' Loyola');  
insert into college values ( 48,'img/colleges/Manhattan_College.jpg',' Manhattan College');  
insert into college values ( 49,'img/colleges/McDaniel_College.jpg',' McDaniel College');  
insert into college values ( 50,'img/colleges/mcfly.jpg',' mcfly');  
insert into college values ( 51,'img/colleges/Miami.jpg',' Miami');  
insert into college values ( 52,'img/colleges/Miami_U_of_Ohio.jpg',' Miami U of Ohio');  
insert into college values ( 53,'img/colleges/michigan_state.jpg',' michigan state');  
insert into college values ( 54,'img/colleges/Miseracordia_University.jpg',' Miseracordia University');  
insert into college values ( 55,'img/colleges/mississippi_state_university.jpg',' mississippi state university');  
insert into college values ( 56,'img/colleges/Monmouth_University.jpg',' Monmouth University');  
insert into college values ( 57,'img/colleges/Montclair_state.jpg',' Montclair state');  
insert into college values ( 58,'img/colleges/Moravian_College.jpg',' Moravian College');  
insert into college values ( 59,'img/colleges/NC_State.jpg',' NC State');  
insert into college values ( 60,'img/colleges/Northeastern_U.jpg',' Northeastern U');  
insert into college values ( 61,'img/colleges/Notre_Dame.jpg',' Notre Dame');  
insert into college values ( 62,'img/colleges/ohio_state.jpg',' ohio state');  
insert into college values ( 63,'img/colleges/Ohio_University.jpg',' Ohio University');  
insert into college values ( 64,'img/colleges/Old_Dominion_University.jpg',' Old Dominion University');  
insert into college values ( 65,'img/colleges/Penn_State.jpg',' Penn State');  
insert into college values ( 66,'img/colleges/Philadelphia_University.jpg',' Philadelphia University');  
insert into college values ( 67,'img/colleges/Princeton_University.jpg',' Princeton University');  
insert into college values ( 68,'img/colleges/Providence University',' P');  
insert into college values ( 69,'img/colleges/Ramapo.jpg',' Ramapo');  
insert into college values ( 70,'img/colleges/Rider_University.jpg',' Rider University');  
insert into college values ( 71,'img/colleges/Rowan_university.jpg',' Rowan university');  
insert into college values ( 72,'img/colleges/Rutgers.jpg',' Rutgers');  
insert into college values ( 73,'img/colleges/Saint_Josephs.jpg',' Saint Josephs');  
insert into college values ( 74,'img/colleges/Salisbury.jpg',' Salisbury');  
insert into college values ( 75,'img/colleges/San_Diego_State.jpg',' San Diego State');  
insert into college values ( 76,'img/colleges/Seton_Hall.jpg',' Seton Hall');  
insert into college values ( 77,'img/colleges/Shippensburg_U.jpg',' Shippensburg U');  
insert into college values ( 78,'img/colleges/Slippery_Rock_U.jpg',' Slippery Rock U');  
insert into college values ( 79,'img/colleges/South_Carolina.jpg',' South Carolina');  
insert into college values ( 80,'img/colleges/Stanford.jpg',' Stanford');  
insert into college values ( 81,'img/colleges/Stevens_Institute_of_Technology.jpg',' Stevens Institute of Technology');  
insert into college values ( 82,'img/colleges/Stony_Brook_u.jpg',' Stony Brook u');  
insert into college values ( 83,'img/colleges/Syracuse.jpg',' Syracuse');  
insert into college values ( 84,'img/colleges/Temple_University.jpg',' Temple University');  
insert into college values ( 85,'img/colleges/Texas_AM_University.jpg',' Texas AM University');  
insert into college values ( 86,'img/colleges/The_Citadel.jpg',' The Citadel');  
insert into college values ( 87,'img/colleges/The_College_of_New_Jersey.jpg',' The College of New Jersey');  
insert into college values ( 88,'img/colleges/Thumbs.db',' Thumbs');  
insert into college values ( 89,'img/colleges/Towson_University.jpg',' Towson University');  
insert into college values ( 90,'img/colleges/UCLA.jpg',' UCLA');  
insert into college values ( 91,'img/colleges/University_of_ Buffalo.jpg',' University of  Buffalo');  
insert into college values ( 92,'img/colleges/University_of_Arizona.jpg',' University of Arizona');  
insert into college values ( 93,'img/colleges/University_of_Central_Florida.jpg',' University of Central Florida');  
insert into college values ( 94,'img/colleges/University_of_Cincinnati.jpg',' University of Cincinnati');  
insert into college values ( 95,'img/colleges/University_of_Colorado.jpg',' University of Colorado');  
insert into college values ( 96,'img/colleges/University_of_Connecticut.jpg',' University of Connecticut');  
insert into college values ( 97,'img/colleges/university_of_deleware.jpg',' university of deleware');  
insert into college values ( 98,'img/colleges/university_of_Florida.jpg',' university of Florida');  
insert into college values ( 99,'img/colleges/University_of_Georgia.jpg',' University of Georgia');  
insert into college values ( 100,'img/colleges/University_of_Houston.jpg',' University of Houston');  
insert into college values ( 101,'img/colleges/University_of_Illinois.jpg',' University of Illinois');  
insert into college values ( 102,'img/colleges/University_of_Kansas.jpg',' University of Kansas');  
insert into college values ( 103,'img/colleges/University_of_Maine.jpg',' University of Maine');  
insert into college values ( 104,'img/colleges/university_of_maryland.jpg',' university of maryland');  
insert into college values ( 105,'img/colleges/University_of_Michigan.jpg',' University of Michigan');  
insert into college values ( 106,'img/colleges/University_of_Minnesota.jpg',' University of Minnesota');  
insert into college values ( 107,'img/colleges/University_of_Mississippi.jpg',' University of Mississippi');  
insert into college values ( 108,'img/colleges/University_of_New_Hampshire.jpg',' University of New Hampshire');  
insert into college values ( 109,'img/colleges/University_of_New_Haven.jpg',' University of New Haven');  
insert into college values ( 110,'img/colleges/University_of_North_Carolina.jpg',' University of North Carolina');  
insert into college values ( 111,'img/colleges/University_of_Pittsburgh.jpg',' University of Pittsburgh');  
insert into college values ( 112,'img/colleges/University_of_Rhode_Island.jpg',' University of Rhode Island');  
insert into college values ( 113,'img/colleges/University_of_Richmond.jpg',' University of Richmond');  
insert into college values ( 114,'img/colleges/University_of_Scranton.jpg',' University of Scranton');  
insert into college values ( 115,'img/colleges/University_of_Tampa.jpg',' University of Tampa');  
insert into college values ( 116,'img/colleges/university_of_virginia.jpg',' university of virginia');  
insert into college values ( 117,'img/colleges/UNLV.jpg',' UNLV');  
insert into college values ( 118,'img/colleges/UPENN.jpg',' UPENN');  
insert into college values ( 119,'img/colleges/USC.jpg',' USC');  
insert into college values ( 120,'img/colleges/VCU.jpg',' VCU');  
insert into college values ( 121,'img/colleges/Villanova_University.jpg',' Villanova University');  
insert into college values ( 122,'img/colleges/Virginia_Tech.jpg',' Virginia Tech');  
insert into college values ( 123,'img/colleges/Wake_Forest_University.jpg',' Wake Forest University');  
insert into college values ( 124,'img/colleges/Western_Carolina_U.jpg',' Western Carolina U');  
insert into college values ( 125,'img/colleges/West_Chester_University.jpg',' West Chester University');  
insert into college values ( 126,'img/colleges/Widener_University.jpg',' Widener University');  
insert into college values ( 127,'img/colleges/William_Patterson_U.jpg',' William Patterson U');  
insert into college values ( 128,'img/colleges/Wisconsin.jpg',' Wisconsin');  
insert into college values ( 129,'img/colleges/WVU.jpg',' WVU');  
insert into college values ( 130,'img/colleges/Xavier_University.jpg',' Xavier University');  
insert into college values ( 131,'img/colleges/Yale_University.jpg',' Yale University'); 