use motedb;
SET FOREIGN_KEY_CHECKS=0;
delete from country;
delete from language;
delete from college;
delete from profile;
delete from type;
delete from tag;
delete from source_objects;
delete from aggregation_source;
delete from aggregation;
delete from post;
delete from post_user_like;
delete from post_user_view;
delete from profile_has_friend;
delete from locale;
delete from ssa_coefficient_parameters;
delete from post_has_tag;

commit;
SET FOREIGN_KEY_CHECKS=1;