use cldb;

insert into clcollege values ( 2,'img/Albright_College.jpg',' Albright College');  
insert into clcollege values ( 3,'img/American_University.jpg',' American University');  
insert into clcollege values ( 4,'img/Arizona_State.jpg',' Arizona State');  
insert into clcollege values ( 5,'img/Assumption_College.jpg',' Assumption College');  
insert into clcollege values ( 6,'img/Bentley_University.jpg',' Bentley University');  
insert into clcollege values ( 7,'img/Binghamton_University.jpg',' Binghamton University');  
insert into clcollege values ( 8,'img/Bloomsburg_U.jpg',' Bloomsburg U');  
insert into clcollege values ( 9,'img/Boston_College.jpg',' Boston College');  
insert into clcollege values ( 10,'img/Boston_University.jpg',' Boston University');  
insert into clcollege values ( 11,'img/Bucknell_University.jpg',' Bucknell University');  
insert into clcollege values ( 12,'img/Carnegie_Mellon_U.jpg',' Carnegie Mellon U');  
insert into clcollege values ( 13,'img/Centenary_College.jpg',' Centenary College');  
insert into clcollege values ( 14,'img/Clemson_University.jpg',' Clemson University');  
insert into clcollege values ( 15,'img/Coastal_Carolina.jpg',' Coastal Carolina');  
insert into clcollege values ( 16,'img/College_of_Charleston.jpg',' College of Charleston');  
insert into clcollege values ( 17,'img/Colorado_School_of_Mines.jpg',' Colorado School of Mines');  
insert into clcollege values ( 18,'img/Colorado_State_University.jpg',' Colorado State University');  
insert into clcollege values ( 19,'img/County_College_of_Morris.jpg',' County College of Morris');  
insert into clcollege values ( 20,'img/DeSales_University.jpg',' DeSales University');  
insert into clcollege values ( 21,'img/Dickinson_College.jpg',' Dickinson College');  
insert into clcollege values ( 22,'img/Drexel_U.jpg',' Drexel U');  
insert into clcollege values ( 23,'img/Duke_University.jpg',' Duke University');  
insert into clcollege values ( 24,'img/East_Carolina_University.jpg',' East Carolina University');  
insert into clcollege values ( 25,'img/East_Stroudsburg_University.jpg',' East Stroudsburg University');  
insert into clcollege values ( 26,'img/Elon_University.jpg',' Elon University');  
insert into clcollege values ( 27,'img/Farleigh_Dickinson_U.jpg',' Farleigh Dickinson U');  
insert into clcollege values ( 28,'img/Florida_College.jpg',' Florida College');  
insert into clcollege values ( 29,'img/Florida_State_U.jpg',' Florida State U');  
insert into clcollege values ( 30,'img/George_Washington_University.jpg',' George Washington University');  
insert into clcollege values ( 31,'img/High_Point_University.jpg',' High Point University');  
insert into clcollege values ( 32,'img/Hofstra_U.jpg',' Hofstra U');  
insert into clcollege values ( 33,'img/Indiana_University.jpg',' Indiana University');  
insert into clcollege values ( 34,'img/Indiana_University_of_Pennsylvania.jpg',' Indiana University of Pennsylvania');  
insert into clcollege values ( 35,'img/ionic.png',' ionic');  
insert into clcollege values ( 36,'img/Iowa.jpg',' Iowa');  
insert into clcollege values ( 37,'img/Iowa_State.jpg',' Iowa State');  
insert into clcollege values ( 38,'img/JMU.jpg',' JMU');  
insert into clcollege values ( 39,'img/Johns_Hopkins_U.jpg',' Johns Hopkins U');  
insert into clcollege values ( 40,'img/Kean_University.jpg',' Kean University');  
insert into clcollege values ( 41,'img/Kent_State_University.jpg',' Kent State University');  
insert into clcollege values ( 42,'img/Kings_College.jpg',' King''s College');  
insert into clcollege values ( 43,'img/Kutztown_University.jpg',' Kutztown University');  
insert into clcollege values ( 44,'img/La_Salle_University.jpg',' La Salle University');  
insert into clcollege values ( 45,'img/Lehigh_University.jpg',' Lehigh University');  
insert into clcollege values ( 46,'img/Liberty_University.jpg',' Liberty University');  
insert into clcollege values ( 47,'img/Lock_Haven_u.jpg',' Lock Haven u');  
insert into clcollege values ( 48,'img/Loyola.jpg',' Loyola');  
insert into clcollege values ( 49,'img/Manhattan_College.jpg',' Manhattan College');  
insert into clcollege values ( 50,'img/McDaniel_College.jpg',' McDaniel College');  
insert into clcollege values ( 51,'img/mcfly.jpg',' mcfly');  
insert into clcollege values ( 52,'img/Miami.jpg',' Miami');  
insert into clcollege values ( 53,'img/Miami_U_of_Ohio.jpg',' Miami U of Ohio');  
insert into clcollege values ( 54,'img/michigan_state.jpg',' michigan state');  
insert into clcollege values ( 55,'img/Miseracordia_University.jpg',' Miseracordia University');  
insert into clcollege values ( 56,'img/mississippi_state_university.jpg',' mississippi state university');  
insert into clcollege values ( 57,'img/Monmouth_University.jpg',' Monmouth University');  
insert into clcollege values ( 58,'img/Montclair_state.jpg',' Montclair state');  
insert into clcollege values ( 59,'img/Moravian_College.jpg',' Moravian College');  
insert into clcollege values ( 60,'img/NC_State.jpg',' NC State');  
insert into clcollege values ( 61,'img/Northeastern_U.jpg',' Northeastern U');  
insert into clcollege values ( 62,'img/Notre_Dame.jpg',' Notre Dame');  
insert into clcollege values ( 63,'img/ohio_state.jpg',' ohio state');  
insert into clcollege values ( 64,'img/Ohio_University.jpg',' Ohio University');  
insert into clcollege values ( 65,'img/Old_Dominion_University.jpg',' Old Dominion University');  
insert into clcollege values ( 66,'img/Penn_State.jpg',' Penn State');  
insert into clcollege values ( 67,'img/Philadelphia_University.jpg',' Philadelphia University');  
insert into clcollege values ( 68,'img/Princeton_University.jpg',' Princeton University');  
insert into clcollege values ( 69,'img/Providence University',' P');  
insert into clcollege values ( 70,'img/Ramapo.jpg',' Ramapo');  
insert into clcollege values ( 71,'img/Rider_University.jpg',' Rider University');  
insert into clcollege values ( 72,'img/Rowan_university.jpg',' Rowan university');  
insert into clcollege values ( 73,'img/Rutgers.jpg',' Rutgers');  
insert into clcollege values ( 74,'img/Saint_Josephs.jpg',' Saint Josephs');  
insert into clcollege values ( 75,'img/Salisbury.jpg',' Salisbury');  
insert into clcollege values ( 76,'img/San_Diego_State.jpg',' San Diego State');  
insert into clcollege values ( 77,'img/Seton_Hall.jpg',' Seton Hall');  
insert into clcollege values ( 78,'img/Shippensburg_U.jpg',' Shippensburg U');  
insert into clcollege values ( 79,'img/Slippery_Rock_U.jpg',' Slippery Rock U');  
insert into clcollege values ( 80,'img/South_Carolina.jpg',' South Carolina');  
insert into clcollege values ( 81,'img/Stanford.jpg',' Stanford');  
insert into clcollege values ( 82,'img/Stevens_Institute_of_Technology.jpg',' Stevens Institute of Technology');  
insert into clcollege values ( 83,'img/Stony_Brook_u.jpg',' Stony Brook u');  
insert into clcollege values ( 84,'img/Syracuse.jpg',' Syracuse');  
insert into clcollege values ( 85,'img/Temple_University.jpg',' Temple University');  
insert into clcollege values ( 86,'img/Texas_AM_University.jpg',' Texas AM University');  
insert into clcollege values ( 87,'img/The_Citadel.jpg',' The Citadel');  
insert into clcollege values ( 88,'img/The_College_of_New_Jersey.jpg',' The College of New Jersey');  
insert into clcollege values ( 89,'img/Thumbs.db',' Thumbs');  
insert into clcollege values ( 90,'img/Towson_University.jpg',' Towson University');  
insert into clcollege values ( 91,'img/UCLA.jpg',' UCLA');  
insert into clcollege values ( 92,'img/University_of_ Buffalo.jpg',' University of  Buffalo');  
insert into clcollege values ( 93,'img/University_of_Arizona.jpg',' University of Arizona');  
insert into clcollege values ( 94,'img/University_of_Central_Florida.jpg',' University of Central Florida');  
insert into clcollege values ( 95,'img/University_of_Cincinnati.jpg',' University of Cincinnati');  
insert into clcollege values ( 96,'img/University_of_Colorado.jpg',' University of Colorado');  
insert into clcollege values ( 97,'img/University_of_Connecticut.jpg',' University of Connecticut');  
insert into clcollege values ( 98,'img/university_of_deleware.jpg',' university of deleware');  
insert into clcollege values ( 99,'img/university_of_Florida.jpg',' university of Florida');  
insert into clcollege values ( 100,'img/University_of_Georgia.jpg',' University of Georgia');  
insert into clcollege values ( 101,'img/University_of_Houston.jpg',' University of Houston');  
insert into clcollege values ( 102,'img/University_of_Illinois.jpg',' University of Illinois');  
insert into clcollege values ( 103,'img/University_of_Kansas.jpg',' University of Kansas');  
insert into clcollege values ( 104,'img/University_of_Maine.jpg',' University of Maine');  
insert into clcollege values ( 105,'img/university_of_maryland.jpg',' university of maryland');  
insert into clcollege values ( 106,'img/University_of_Michigan.jpg',' University of Michigan');  
insert into clcollege values ( 107,'img/University_of_Minnesota.jpg',' University of Minnesota');  
insert into clcollege values ( 108,'img/University_of_Mississippi.jpg',' University of Mississippi');  
insert into clcollege values ( 109,'img/University_of_New_Hampshire.jpg',' University of New Hampshire');  
insert into clcollege values ( 110,'img/University_of_New_Haven.jpg',' University of New Haven');  
insert into clcollege values ( 111,'img/University_of_North_Carolina.jpg',' University of North Carolina');  
insert into clcollege values ( 112,'img/University_of_Pittsburgh.jpg',' University of Pittsburgh');  
insert into clcollege values ( 113,'img/University_of_Rhode_Island.jpg',' University of Rhode Island');  
insert into clcollege values ( 114,'img/University_of_Richmond.jpg',' University of Richmond');  
insert into clcollege values ( 115,'img/University_of_Scranton.jpg',' University of Scranton');  
insert into clcollege values ( 116,'img/University_of_Tampa.jpg',' University of Tampa');  
insert into clcollege values ( 117,'img/university_of_virginia.jpg',' university of virginia');  
insert into clcollege values ( 118,'img/UNLV.jpg',' UNLV');  
insert into clcollege values ( 119,'img/UPENN.jpg',' UPENN');  
insert into clcollege values ( 120,'img/USC.jpg',' USC');  
insert into clcollege values ( 121,'img/VCU.jpg',' VCU');  
insert into clcollege values ( 122,'img/Villanova_University.jpg',' Villanova University');  
insert into clcollege values ( 123,'img/Virginia_Tech.jpg',' Virginia Tech');  
insert into clcollege values ( 124,'img/Wake_Forest_University.jpg',' Wake Forest University');  
insert into clcollege values ( 125,'img/Western_Carolina_U.jpg',' Western Carolina U');  
insert into clcollege values ( 126,'img/West_Chester_University.jpg',' West Chester University');  
insert into clcollege values ( 127,'img/Widener_University.jpg',' Widener University');  
insert into clcollege values ( 128,'img/William_Patterson_U.jpg',' William Patterson U');  
insert into clcollege values ( 129,'img/Wisconsin.jpg',' Wisconsin');  
insert into clcollege values ( 130,'img/WVU.jpg',' WVU');  
insert into clcollege values ( 131,'img/Xavier_University.jpg',' Xavier University');  
insert into clcollege values ( 132,'img/Yale_University.jpg',' Yale University'); 